-- select * from items order by price ASC;
-- select * from items where price >= 80 order by price DESC;
-- select * from customers order by first_name asc limit(3);
-- select last_name from customers order by last_name DESC;